import type { Metadata } from "next";
import { DM_Mono, Geom } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const geom = Geom({
	variable: "--font-heading",
	subsets: ["latin"],
	display: "swap",
});

const dmMono = DM_Mono({
	variable: "--font-body",
	subsets: ["latin"],
	weight: ["300", "400", "500"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={cn(
				"h-full antialiased font-mono",
				geom.variable,
				dmMono.variable,
			)}
		>
			<body className="min-h-full flex flex-col">{children}</body>
		</html>
	);
}
