import type { Metadata } from "next";
import { DM_Mono, Georama } from "next/font/google";
import "./globals.css";
import { SideBar } from "@/components/layout/sidebar/SideBar";
import { getPostTags } from "@/lib/db/queries";
import { cn } from "@/lib/utils";

const georama = Georama({
	variable: "--font-heading",
	subsets: ["latin"],
	display: "swap",
});

const dmMono = DM_Mono({
	variable: "--font-body",
	subsets: ["latin"],
	weight: ["300", "400", "500"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const tags = await getPostTags();

	return (
		<html
			lang="en"
			className={cn(
				"h-full antialiased font-mono",
				georama.variable,
				dmMono.variable,
			)}
		>
			<body className="min-h-full">
				<SideBar tags={tags} />
				<main className="relative z-10 min-w-0 md:pl-80">{children}</main>
			</body>
		</html>
	);
}
